spring:
  application.name: agency
  profiles.active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: Dmitry
    password: Dmitry
  liquibase:
    change-log: db/changelog/changelog.xml
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

server.port: 9000

properties.address: http://localhost:9001

connectTimeoutInSeconds: 30
readTimeoutInSeconds: 60


